sudo: false

android:
  components:
    - tools
    - platform-tools
    - build-tools-26.0.2
    - android-23
    - android-25
    - extra-android-m2repository

before_cache:
    - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock 

cache:
    directories:
        - .nvm
        - $HOME/.gradle/caches/
        - $HOME/.gradle/wrapper/

install:
    - echo no | npm install -g nativescript
    - tns usage-reporting disable
    - tns error-reporting disable
    - echo no | npm install -g grunt-cli
    - npm install
    - grunt compile

matrix:
  include:
    - stage: lint
      language: node_js
      os: linux
      node_js: "6"
      script: grunt lint

    - stage: build
      language: android
      os: linux
      env: 
        - Android="26"
      jdk: oraclejdk8
      before_install: nvm install 6.10.3
      script: "grunt ci:build:android"

    - stage: build
      os: osx
      env: 
        - iOS="10.3"
        - Xcode="8.3"
      osx_image: xcode8.3
      language: node_js 
      node_js: "6"
      jdk: oraclejdk8
      script: "grunt ci:build:ios"

    - stage: webpack
      language: android
      os: linux
      env:
        - Android="26"
        - Platform="Android"
      jdk: oraclejdk8
      before_install: nvm install 6.10.3
      script: "grunt ci:webpack:android"
    
    - stage: webpack
      os: osx
      env: 
        - iOS="10.3"
        - Xcode="8.3"
        - Platform="iOS"
      osx_image: xcode8.3
      language: node_js 
      node_js: "6"
      jdk: oraclejdk8
      script: "grunt ci:webpack:ios"

    - stage: deploy
      if: branch = release
      language: node_js 
      node_js: "6"
      before_deploy:
          - cd bin/dist
      deploy:
        provider: npm
        email: "peter@tangrasoft.com"
        api_key:
            secure: "aJaRODpz7b7k77WmdOG1tlFp3HZopZq6bzKjMwNtWIGlJbmxBGwv/0c63cHRy2JPxPHFHDQVQ4lcrRzXjyz5lB3dq/VSgFq7ydcBkQnNjwgaBBLfyluYAcyt4/qEHRJqJ5oDuV3ReAE5Vb78OoVOUCevbrgPwm8IoDawXHXwUskqvow/hiooaelvpcntAfA/efLYRJqIzrdaNehfIibESrLPD50PWzLlFk4ctkvtmriCe1WLw7pw9bW/86/tjm3MAf39/HhBx/lYh9SAg1KZRtnga7xfphzybx5ZcI6152Bxt+9ICgXimn2r5IjBp8eW09RkksMars3ZwKf1dZSDcUVLKAwYM3tW1Yn/UdWWWGyoRtq/wMnnVW5TvfuNDEOFOVFP2t0SuOjjwgmQuSc5l1GD65PTDEwLHz01kaCXDEF+ErShZt/VgvkcxwqEozxeCmBfhp2Rlaszh31MSCO9bheM17N5z+v0beujQ5yBYKC+oxIrM2b8cpbbmgfYnXVuTuYnRefNmiODnIhYDK5THBEjbjowpJiy/2Ib4wT6gND8b5foyi6vAD143XXtzFfbDx03iOu/2Ye38741tIZHJfW9k4uUdNS4WGHv86+oY3uQ1GZ2WkaVa/M4V7sdimgqPJnnpG3cOtsFz0zFXEpKJ/gVC6zmtQ5Xwyvl6rSzOyc="
        skip_cleanup: true
        on:
          branch: release